### ISSUE TITLE
Is it possible to change Tilte Font or background color in SQL ?

### ISSUE THREAD

**Issue by mvmchp** [RonnyWeiss/APEX-Flip-Cards#1]
I would like to change the Title's Font or Background color with the SQL Query. I'd like to use a case statement to hightlight titles based on data in my image table. 

CASE 
   WHEN Image_Status = 'Important' THEN 'red'
   ELSE 'black'
END as TITLE_FONT_COLOR,

Is this something that can be added?

Thanks

**Comment by RonnyWeiss** [comment]
Hello


When you make scaling in SQL then you can add HTML and can do what you want e.g <span style="color:red">your escaped text</span>

Is that an idea?

LG Ronny

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by mvmchp** [comment]
Sure, that would work, I'll test it on Monday.

Thanks!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
